# SPDX-License-Identifier: GPL-2.0-only

subdir-ccflags-y += -I$(srctree)/drivers/power/oplus

obj-$(CONFIG_POWER_RESET)	+= reset/
obj-$(CONFIG_POWER_SUPPLY)	+= supply/

obj-$(CONFIG_OPLUS_CHARGER)	+= oplus/
